In [95]:
import math
def nthgeom(a,b,c):
    return a*(math.pow(b,(c-1)))

a = 2
b = 2
c = 2

nthgeom(a,b,c)

4.0

In [112]:
#First I create the matrix using randon

In [96]:
a = np.floor(10*np.random.random((3,3)))
print(a)



[[9. 2. 5.]
 [5. 4. 5.]
 [5. 5. 6.]]


In [ ]:
#Them I used Boolean argument

In [97]:
b = a > 4
b

array([[ True, False,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [ ]:
#Finally I make the 3 Geometric Progessions on the matrix using nthgeom

In [105]:
first = nthgeom(9,2,5)

In [106]:
first

144.0

In [107]:
second = nthgeom(5,4,5) 

In [108]:
second

1280.0

In [109]:
thrid = nthgeom(5,5,6)

In [110]:
thrid

15625.0